	<section class="footer_bottom">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 ">
                    <p class="copyright">&copy; Copyright 2020 NLDB | Powered by  <a href="http://www.nldb.gov.lk/">National Livestock Development Board</a></p>
				</div>
				
				<div class="col-lg-6 ">
					<div class="footer_social">
						<ul class="footbot_social">
							<li><a class="fb" href="https://www.facebook.com/nldbs" data-placement="top" data-toggle="tooltip" title="Facbook"><i class="fa fa-facebook"></i></a></li>
							<li><a class="twtr" href="#." data-placement="top" data-toggle="tooltip" title="Twitter"><i class="fa fa-twitter"></i></a></li>

							<li><a class="skype" href="#." data-placement="top" data-toggle="tooltip" title="Skype"><i class="fa fa-skype"></i></a></li>
							<li><a class="rss" href="#." data-placement="top" data-toggle="tooltip" title="RSS"><i class="fa fa-rss"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</section>