<!--start footer-->
<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-md-3 col-lg-3">
                <div class="widget_title">
                    <h4><span>About Us</span></h4>
                </div>
                <div class="widget_content">
                    <p>The National Livestock Development Board was established  in 1973 under the State Agricultural   Corporation Act No.11 of 1972.Its field operations commenced on 1974.Government first milk processing plant was installed in 1954 in Narahenpita.</p>
                    <ul class="contact-details-alt">
                        <li><i class="fa fa-map-marker"></i> <p><strong>Address</strong>: P.O.Box 1748,No 40, Nawala Road,Narahenpita</p></li>
                        <li><i class="fa fa-user"></i> <p><strong>Phone</strong>:+94112501701</p></li><li><i class="fa fa-user"></i> <p><strong>Phone</strong>:+94112501702</p></li>
                        <li><i class="fa fa-envelope"></i> <p><strong>Email</strong>: <a href="mailto:info@nldb.gov.lk">info@nldb.gov.lk</a></p></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-6 col-md-3 col-lg-3">
                <div class="widget_title">
                    <a href="http://www.nldb.gov.lk/resentNews.asp"><h4><span> Recent News</span></h4></a>
                </div>
                <div class="widget_content">
                    <ul class="links">
						
						
						 <li><a href="download/farms/Application Form for Farm Visits .docx">Farm Visits Application<span>January 01, 2020</span></a></li>
                      <!---   <li><a href="download/courses/AppTraining.docx"> Short Term Traning  Application<span>January 01, 2020</span></a></li> --->
						<li><a href="download/breeds/Livestock Application Tamil English Sinhala.pdf"> Application for issue of livestock <span>January 01, 2020</span></a></li>
						<li><a href="download/breeds/Livestock Application Tamil English Sinhala .docx"> Application for issue of livestock <span>January 01, 2020</span></a></li>
                        <!--- <li><a href="download/Bungalow/application.pdf"> Bungalow Reservation Form <span>January 01, 2020</span></a></li> --->
						<li><a href="download/Products/nldb-outlets.pdf">Milk Outlets of NLDB  <span>January 01, 2020</span></a></li>
						<li><a href="download/Products/sale-centers.pdf">NLDB Sale Centers  <span>January 01, 2020</span></a></li>
					<!---	<li><a href="download/Products/How to purchase breeding materials and Poultry chicks.pdf">Purchase Breeding Materials <span>January 01, 2020</span></a></li> --->
						<li><a href="download/breeds/Application for animal issue - Sinhala.pdf">Application for animal issue[Sinhala]  <span>January 01, 2020</span></a></li>
					<!---	<li><a href="download/breeds/application for animal issue-English.pdf">Application for animal issue[English] <span>January 01, 2020</span></a></li> --->
					<!---	<li> <a href="http://www.nldb.gov.lk/download/farms/FMD Alert 3.pdf">FMD ALERT – 3nd Notice   <span>January 07, 2020</span></a></li> --->

                    </ul>
                </div>
            </div>
            <div class="col-sm-6 col-md-3 col-lg-3">
                <div class="widget_title">
                    <h4><span>facebook</span></h4>
                </div>
                <div class="widget_content">
                    <ul class="links">
<li> <a href=https://www.facebook.com/nldb.lk/posts/pfbid02rHkxy3MTkHo858gZDY49TYwKdftmz2rJwaMzFmbfQ9C2EZMzi1A3gyf3KDrHJe3ql?notif_id=1705903150330458&notif_t=feedback_reaction_generic&ref=notif">1st Batch Livestock Technician Course (NVQ LEVEL 4) 2024<span>January 24, 2024</span></a></li>
						<li> <a href="https://www.facebook.com/nldb.lk/posts/3361578557190163">Coconut Distribution in Colombo District <span>April 1, 2020</span></a></li>
						<li> <a href="https://www.facebook.com/nldb.lk/posts/3361578557190163">Coconut Distribution in Colombo District <span>April 1, 2020</span></a></li>
						<li> <a href="https://www.facebook.com/media/set/?set=a.3208992152448805&type=3">Practical Training Training programmes <span>January 28, 2020</span></a></li>
						<li> <a href="https://www.facebook.com/media/set/?set=a.3197564403591580&type=3">Polonthalawa Bawa Bunglow <span>January 23, 2020</span></a></li>
                        <li> <a href="https://www.facebook.com/media/set/?set=a.3132544736760214&type=3">Nelum Wewa Circuit Bungalow <span>December 26 , 2019</span></a></li>
                        <li> <a href="https://www.facebook.com/nldb.lk/posts/3091716240843064">Day Old Broiler Chicks For Sale <span> December 09, 2019</span></a></li>
                    </ul>
                </div>
            </div>

<div class="col-sm-6 col-md-3 col-lg-3">
            <div class="widget_title">
                <h4><span>Footer Gallery</span></h4>
            </div>
            <div class="widget_content">
                <div class="row">
                    <div class="col-xs-3 col-sm-4 col-lg-3">
                        <a href="#imageModal1" data-toggle="modal">
                            <img src="http://www.nldb.gov.lk/images/gallery/11.jpeg" alt="Image 1" width="80" height="80" class="footer-g-t">
                        </a>
                    </div>
                    <div class="col-xs-3 col-sm-4 col-lg-3">
                        <a href="#imageModal2" data-toggle="modal">
                            <img src="http://www.nldb.gov.lk/images/gallery/22.jpeg" alt="Image 2" width="80" height="80" class="footer-g-t">
                        </a>
                    </div>
                    <div class="col-xs-3 col-sm-4 col-lg-3">
                        <a href="#imageModal3" data-toggle="modal">
                            <img src="http://www.nldb.gov.lk/images/gallery/33.jpeg" alt="Image 3" width="80" height="80" class="footer-g-t">
                        </a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-3 col-sm-4 col-lg-3">
                        <a href="#imageModal4" data-toggle="modal">
                            <img src="http://www.nldb.gov.lk/images/gallery/44.jpeg" alt="Image 4" width="80" height="80" class="footer-g-t">
                        </a>
                    </div>
                    <div class="col-xs-3 col-sm-4 col-lg-3">
                        <a href="#imageModal5" data-toggle="modal">
                            <img src="http://www.nldb.gov.lk/images/gallery/55.jpeg" alt="Image 5" width="80" height="80" class="footer-g-t">
                        </a>
                    </div>
                    <div class="col-xs-3 col-sm-4 col-lg-3">
                        <a href="#imageModal6" data-toggle="modal">
                            <img src="http://www.nldb.gov.lk/images/gallery/66.jpeg" alt="Image 6" width="80" height="80" class="footer-g-t">
                        </a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-3 col-sm-4 col-lg-3">
                        <a href="#imageModal7" data-toggle="modal">
                            <img src="http://www.nldb.gov.lk/images/gallery/77.jpeg" alt="Image 7" width="80" height="80" class="footer-g-t">
                        </a>
                    </div>
                    <div class="col-xs-3 col-sm-4 col-lg-3">
                        <a href="#imageModal8" data-toggle="modal">
                            <img src="http://www.nldb.gov.lk/images/gallery/88.jpeg" alt="Image 8" width="80" height="80" class="footer-g-t">
                        </a>
                    </div>
                    <div class="col-xs-3 col-sm-4 col-lg-4">
                        <a href="#imageModal9" data-toggle="modal">
                            <img src="http://www.nldb.gov.lk/images/gallery/99.jpeg" alt="Image 9" width="80" height="80" class="footer-g-t">
                        </a>
                    </div>
 
         
<div class="col-xs-3 col-sm-4 col-lg-3">
                        <a href="#imageModal9" data-toggle="modal">
                            <img src="http://www.nldb.gov.lk/images/Bataatha/1.1.jpeg" alt="Image 9" width="80" height="80" class="footer-g-t">
                        </a>
                    </div>
<div class="col-xs-3 col-sm-4 col-lg-3">
                        <a href="#imageModal9" data-toggle="modal">
                            <img src="http://www.nldb.gov.lk/images/Bataatha/2.1.jpeg" alt="Image 9" width="80" height="80" class="footer-g-t">
                        </a>
                    </div>
<div class="col-xs-3 col-sm-4 col-lg-4">
                        <a href="#imageModal9" data-toggle="modal">
                            <img src="http://www.nldb.gov.lk/images/Bataatha/3.1.jpeg" alt="Image 9" width="80" height="80" class="footer-g-t">
                        </a>
                    </div>
<div class="col-xs-3 col-sm-4 col-lg-3">
                        <a href="#imageModal9" data-toggle="modal">
                            <img src="http://www.nldb.gov.lk/images/Bataatha/4.1.jpeg" alt="Image 9" width="80" height="80" class="footer-g-t">
                        </a>
                    </div>
<div class="col-xs-3 col-sm-4 col-lg-3">
                        <a href="#imageModal9" data-toggle="modal">
                            <img src="http://www.nldb.gov.lk/images/Bataatha/5.1.jpeg" alt="Image 9" width="80" height="80" class="footer-g-t">
                        </a>
                    </div>
<div class="col-xs-3 col-sm-4 col-lg-4">
                        <a href="#imageModal9" data-toggle="modal">
                            <img src="http://www.nldb.gov.lk/images/Bataatha/6.1.jpeg" alt="Image 9" width="80" height="80" class="footer-g-t">
                        </a>
                    </div>
<div class="col-xs-3 col-sm-4 col-lg-3">
                        <a href="#imageModal9" data-toggle="modal">
                            <img src="http://www.nldb.gov.lk/images/Bataatha/7.1.jpeg" alt="Image 9" width="80" height="80" class="footer-g-t">
                        </a>
                    </div>
<div class="col-xs-3 col-sm-4 col-lg-3">
                        <a href="#imageModal9" data-toggle="modal">
                            <img src="http://www.nldb.gov.lk/images/Bataatha/8.1.jpeg" alt="Image 9" width="80" height="80" class="footer-g-t">
                        </a>
                    </div>
<div class="col-xs-3 col-sm-4 col-lg-3">
                        <a href="#imageModal9" data-toggle="modal">
                            <img src="http://www.nldb.gov.lk/images/Bataatha/9.1.jpeg" alt="Image 9" width="80" height="80" class="footer-g-t">
                        </a>
                    </div>
       </div>
            </div>
        </div>

<!-- Modals for the images -->
<div class="modal fade" id="imageModal1" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <img src="http://nldb.yourwebhosting.com/public_html/nldbhn/images/gallery/1.jpeg" alt="Image 1" class="popup-image">
        </div>
    </div>
</div>
<div class="modal fade" id="imageModal2" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <img src="http://nldb.yourwebhosting.com/public_html/nldbhn/images/gallery/2.jpeg" alt="Image 2" class="popup-image">
        </div>
    </div>
</div>
<div class="modal fade" id="imageModal3" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <img src="http://nldb.yourwebhosting.com/public_html/nldbhn/images/gallery/3.jpeg" alt="Image 3" class="popup-image">
        </div>
    </div>
</div>
<div class="modal fade" id="imageModal4" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class modal-content">
            <img src="http://nldb.yourwebhosting.com/public_html/nldbhn/images/gallery/4.jpeg" alt="Image 4" class="popup-image">
        </div>
    </div>
</div>
<div class="modal fade" id="imageModal5" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <img src="http://nldb.yourwebhosting.com/public_html/nldbhn/images/gallery/5.jpeg" alt="Image 5" class="popup-image">
        </div>
    </div>
</div>
<div class="modal fade" id="imageModal6" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <img src="http://nldb.yourwebhosting.com/public_html/nldbhn/images/gallery/6.jpeg" alt="Image 6" class="popup-image">
        </div>
    </div>
</div>
<div class="modal fade" id="imageModal7" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <img src="http://nldb.yourwebhosting.com/public_html/nldbhn/images/gallery/7.jpeg" alt="Image 7" class="popup-image">
        </div>
    </div>
</div>
<div class="modal fade" id="imageModal8" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <img src="http://nldb.yourwebhosting.com/public_html/nldbhn/images/gallery/8.jpeg" alt="Image 8" class="popup-image">
        </div>
    </div>
</div>

<!-- Modals for the images -->
<div class="modal fade" id="imageModal9" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
   
     <div id="product-slider" class="carousel slide" data-ride="carousel">
    <!-- Indicators (optional) -->
    <ol class="carousel-indicators">
        <li data-target="#product-slider" data-slide-to="0" class="active"></li>
        <li data-target="#product-slider" data-slide-to="1"></li>
        <li data-target="#product-slider" data-slide-to="2"></li>
        <!-- Add more indicators as needed -->
    </ol>

    <!-- Slides -->
    <div class="carousel-inner">
        <div class="item active">
            <img src="http://nldb.yourwebhosting.com/public_html/nldbhn/images/Bataatha/1.jpeg" alt="Product 1">
            <div class="carousel-caption">
                
            </div>
        </div>
        <div class="item">
            <img src="http://nldb.yourwebhosting.com/public_html/nldbhn/images/gallery/10.jpeg" alt="Product 2">
            <div class="carousel-caption">
               
            </div>
        </div>

        <div class="item">
            <img src="http://nldb.yourwebhosting.com/public_html/nldbhn/images/gallery/111.jpeg" alt="Product 2">
            <div class="carousel-caption">
               
            </div>
        </div>

        <div class="item">
            <img src="http://nldb.yourwebhosting.com/public_html/nldbhn/images/gallery/12.jpeg" alt="Product 2">
            <div class="carousel-caption">
               
            </div>
        </div>

        <div class="item">
            <img src="http://nldb.yourwebhosting.com/public_html/nldbhn/images/gallery/13.jpeg" alt="Product 2">
            <div class="carousel-caption">
               
            </div>
        </div>

        <div class="item">
            <img src="http://nldb.yourwebhosting.com/public_html/nldbhn/images/gallery/14.jpeg" alt="Product 2">
            <div class="carousel-caption">
               
            </div>
        </div>

        <div class="item">
            <img src="http://nldb.yourwebhosting.com/public_html/nldbhn/images/gallery/15.jpeg" alt="Product 2">
            <div class="carousel-caption">
               
            </div>
        </div>

        <div class="item">
            <img src="http://nldb.yourwebhosting.com/public_html/nldbhn/images/gallery/16.jpeg" alt="Product 2">
            <div class="carousel-caption">
               
            </div>
        </div>

        <div class="item">
            <img src="http://nldb.yourwebhosting.com/public_html/nldbhn/images/gallery/17.jpeg" alt="Product 2">
            <div class="carousel-caption">
               
            </div>
        </div>

        <div class="item">
            <img src="http://nldb.yourwebhosting.com/public_html/nldbhn/images/gallery/18.jpeg" alt="Product 2">
            <div class="carousel-caption">
               
            </div>
        </div>

        <div class="item">
            <img src="http://nldb.yourwebhosting.com/public_html/nldbhn/images/gallery/19.jpeg" alt="Product 2">
            <div class="carousel-caption">
               
            </div>
        </div>

        <div class="item">
            <img src="http://nldb.yourwebhosting.com/public_html/nldbhn/images/gallery/20.jpeg" alt="Product 2">
            <div class="carousel-caption">
               
            </div>
        </div>

        <div class="item">
            <img src="http://nldb.yourwebhosting.com/public_html/nldbhn/images/gallery/21.jpeg" alt="Product 2">
            <div class="carousel-caption">
               
            </div>
        </div>

        <div class="item">
            <img src="http://nldb.yourwebhosting.com/public_html/nldbhn/images/gallery/222.jpeg" alt="Product 2">
            <div class="carousel-caption">
               
            </div>
        </div>

        <div class="item">
            <img src="http://nldb.yourwebhosting.com/public_html/nldbhn/images/gallery/23.jpeg" alt="Product 2">
            <div class="carousel-caption">
               
            </div>
        </div>

        <div class="item">
            <img src="http://nldb.yourwebhosting.com/public_html/nldbhn/images/gallery/24.jpeg" alt="Product 2">
            <div class="carousel-caption">
               
            </div>
        </div>

        <div class="item">
            <img src="http://nldb.yourwebhosting.com/public_html/nldbhn/images/gallery/25.jpeg" alt="Product 2">
            <div class="carousel-caption">
               
            </div>
        </div>

        <div class="item">
            <img src="http://nldb.yourwebhosting.com/public_html/nldbhn/images/gallery/26.jpeg" alt="Product 2">
            <div class="carousel-caption">
               
            </div>
        </div>

        <div class="item">
            <img src="http://nldb.yourwebhosting.com/public_html/nldbhn/images/gallery/27.jpeg" alt="Product 2">
            <div class="carousel-caption">
               
            </div>
        </div>

        <div class="item">
            <img src="http://nldb.yourwebhosting.com/public_html/nldbhn/images/Bataatha/2.jpeg" alt="Product 2">
            <div class="carousel-caption">
               
            </div>
        </div>
<div class="item">
            <img src="http://nldb.yourwebhosting.com/public_html/nldbhn/images/Bataatha/1.jpeg" alt="Product 2">
            <div class="carousel-caption">
               
            </div>
        </div>


        <!-- Add more slides as needed -->
    </div>

    <!-- Controls (optional) -->
    <a class="left carousel-control" href="#product-slider" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#product-slider" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
</div>


           
        </div>
    </div>
</div>





        </div>
    </div>
</footer>
<!--end footer-->