<div id="top-bar">
    <div class="container">
        <div class="row">
            <div class="col-sm-7 hidden-xs top-info">
                <span><i class="fa fa-phone"></i>Phone: +94112501701</span>
                <span><i class="fa fa-envelope"></i>Email: info@nldb.lk</span>
            </div>
            <div class="col-sm-5 top-info">
                <ul>
                    <li><a href="" class="my-tweet"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="https://www.facebook.com/nldb.lk/" class="my-facebook"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="" class="my-skype"><i class="fa fa-skype"></i></a></li>
                    <li><a href="" class="my-pint"><i class="fa fa-pinterest"></i></a></li>
                    <li><a href="" class="my-rss"><i class="fa fa-rss"></i></a></li>
                    <li><a href="" class="my-google"><i class="fa fa-google-plus"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- LOGO bar -->
<div id="logo-bar" class="clearfix">
    <!-- Container -->
    <div class="container">
        <div class="row">
            <!-- Logo / Mobile Menu -->
            <div class="col-xs-12">
                <div id="logo">
                    <h1><a href="http://www.nldb.gov.lk/index.asp"><img src="http://www.nldb.gov.lk/images/logo.png" alt="Velocity" /></a></h1>
                </div>
            </div>
        </div>
    </div>
    <!-- Container / End -->
</div>
<!--LOGO bar / End-->

<!-- Navigation
================================================== -->
<div class="navbar navbar-default navbar-static-top container" role="navigation">
    <!--  <div class="container">-->
    <div class="row">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                
                <li><a href="http://www.nldb.gov.lk/index.asp">Home</a></li>
                
<li><a href="about.asp" >About Us</a>
<ul class="dropdown-menu">
<li><a href="http://www.nldb.gov.lk/about.asp">About</a></li>
    <li><a href="http://www.nldb.gov.lk/DirectorBoard.asp">Director Board</a></li> 
    <li><a href="http://www.nldb.gov.lk/members.asp">Our Members</a></li> 
            <li><a href="http://www.nldb.gov.lk/procurements.asp">Procurements</a></li> 
                        <!--- <li><a href="http://www.nldb.gov.lk/HeadOffice.asp">Head Office</a></li> --->
                     <!---  <li><a href="http://www.nldb.gov.lk/FarmStaff.asp">Farms </a></li> --->
                      <!--- <li><a href="http://www.agrimin.gov.lk/web/">Ministry</a></li> --->
                        <li><a href="http://www.nldb.gov.lk/Projects.asp">Projects</a></li>
                        <li><a href="https://www.facebook.com/pg/nldb.lk/photos/?tab=album&album_id=993755717305804">Gallery</a></li>
                    </ul>
                </li>
                <li><a href="http://www.nldb.gov.lk/Bungallow/BungallowMap.asp" >Bungalows</a>
                    <ul class="dropdown-menu">
                        <li><a href="http://www.nldb.gov.lk/Bungallow/Nikawaratiya_Bungallow.asp">Nikaweratiya</a></li>
                        <li><a href="http://www.nldb.gov.lk/Bungallow/Bopaththalawa_Bungallow.asp">Bopaththalawa</a></li>
                        <li><a href="http://www.nldb.gov.lk/Bungallow/Nelumwewa_Bungallow.asp">Nelumwewa(Polonnaruwa)</a></li>
                        <li><a href="http://www.nldb.gov.lk/Bungallow/Galpokuna_Bungallow.asp">Galpokuna</a></li>
                        <li><a href="http://www.nldb.gov.lk/Bungallow/MLDC_Bungallow.asp">MLDC</a></li>
                        <li><a href="http://www.nldb.gov.lk/Bungallow/Weerawila_Bungallow.asp">Weerawila</a></li>
                        <li><a href="http://www.nldb.gov.lk/Bungallow/Anuradhapura_Bungallow.asp">Anuradhapura</a></li>
                        
                        <li><a href="http://www.nldb.gov.lk/Bungallow/BungallowMap.asp">More . . .</a></li>
                        
                    </ul>
                </li>
                <li><a href="http://www.nldb.gov.lk/Farm/FarmMap.asp">Farms</a>
                    <ul class="dropdown-menu">
                          <li><a href="http://www.nldb.gov.lk/Farm/AndigamaFarm.asp">Andigama</a></li>
                          <li><a href="http://www.nldb.gov.lk/Farm/BopathalawaFarm.asp">Bopaththalawa</a></li>
                          <li><a href="http://www.nldb.gov.lk/Farm/Galpokuna Farm.asp">Galpokuna</a></li>
                          <li><a href="http://www.nldb.gov.lk/Farm/KoulwewaFarm.asp">Koulwewa</a></li>
                          <li><a href="http://www.nldb.gov.lk/Farm/NikaweratiyaFarm.asp">Nikaweratiya</a></li>
                          <li><a href="http://www.nldb.gov.lk/Farm/FarmMap.asp">More . . .</a></li>
                    </ul>
                </li>
                    <li><a href="http://www.nldb.gov.lk/products/Products.asp">Products</a></li>
                <li>
                    <a href="#">Livestock breeds</a>
                    <ul class="dropdown-menu">
                        <li><a href="http://www.nldb.gov.lk/Breeds/NeatCattles.asp">Neat cattle</a></li>
                        <li><a href="http://www.nldb.gov.lk/Breeds/BuffaloBreeds.asp">Buffalow Breeds</a></li>
                        <li><a href="http://www.nldb.gov.lk/Breeds/GoatsBreeds.asp">Goats Breeds</a></li>
                        <li><a href="http://www.nldb.gov.lk/Breeds/PigBreeds.asp">Pigs Breeds</a></li>
                        <li><a href="http://www.nldb.gov.lk/Breeds/SheepBreeds.asp">Sheep Breeds</a></li>
                    </ul>
                    
                </li>
                    <li><a href="#">Courses</a>
                        <ul class="dropdown-menu">
                            <li><a href="http://www.nldb.gov.lk/courses/TrainingC.asp">Practical Training &amp;
                                            Short Term Training programme </a></li>
                            <li><a href="http://www.nldb.gov.lk/courses/ShortTC.asp">Short Term Training programme</a></li>

                        </ul>
                    </li>
                <li><a href="http://www.nldb.gov.lk/contact.asp">Contact us</a>
                    <ul class="dropdown-menu">
                       <li><a href="http://www.nldb.gov.lk/contact.asp">Contact</a></li>

                    </ul>
                </li>

                    <li><a href="#">Downloads</a>
                        <ul class="dropdown-menu">
							<li><a href="download/Assistantfarmmanager.pdf" download>Assistant Manager Vacancies </a></li>
                              <li><a href="download/Purchase-of-Feed-Ingredients-for-NLDB-Farms.pdf" download>Purchase of Feed Ingredients for NLDB Farms</a></li>
                              <li><a href="download/Purchase-of-Feed ingredient-(Grain Maize)-for-NLDB-Farms.pdf" download>Purchase of Feed ingredient (Grain Maize) for NLDB Farms</a></li>
                          <li><a href="download/Purchase-of-Broiler.pdf" download>Purchase of Broiler Breeder Parent Chicks</a></li>   
                          <li><a href="download/Application-NVQ-4-LT.pdf" download>Application NVQ-4 LT.pdf</a></li>  
                          <li><a href="download/Annual-Report-2018.pdf" download>Annual Report 2018.pdf </a></li>


                        </ul>
                    </li>

          </li>
    <li><a href="#">News</a>
                        <ul class="dropdown-menu">
                              <li><a href="https://www.youtube.com/live/1JC_MmBVX3k?si=X03rO9SgSvTRhztS" download>BIG FOCUS | වියළි කාලගුණය මෙරට පශු ක්ෂේත්‍රයට කරන බලපෑම</a></li>
                               <li><a href="https://www.facebook.com/nldb.lk/posts/pfbid02rHkxy3MTkHo858gZDY49TYwKdftmz2rJwaMzFmbfQ9C2EZMzi1A3gyf3KDrHJe3ql?notif_id=1705903150330458&notif_t=feedback_reaction_generic&ref=notif" download>ජාතික පශු සම්පත් සංවර්ධන මණ්ඩලය විසින් ප්‍රථම වරට ආරම්භ කරන ලද පශු සම්පත් තාක්ෂණික ශිල්පි පාඨමාලාව</a></li>
   
                                            


                        </ul>
                    </li>

                </li>
                  
                <!-- <li><a href="http://www.nldb.gov.lk/resentNews.asp">Resent Posts</a></li> -->
                <!-- <li><a href="http://www.nldb.gov.lk/siteMap.asp">Site map</a></li> -->
                
          
            </ul> 
          
        </div>
    </div><!--/.row -->
    <!--</div>--><!--/.container -->

</div>