 <section class="latest_work">
        <div class="container">
            <div class="row sub_content">
                <div class="carousel-intro">
                    <div class="col-md-12">
                        <div class="dividerHeading">
                            <h4><span>Products </span></h4>
                        </div>
                        <div class="carousel-navi">
                            <div id="work-prev" class="arrow-left jcarousel-prev"><i class="fa fa-angle-left"></i></div>
                            <div id="work-next" class="arrow-right jcarousel-next"><i class="fa fa-angle-right"></i></div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>

                <div class="jcarousel recent-work-jc">
                    <ul class="jcarousel-list">
                        <!-- Recent Work Item -->
                        <li class="col-sm-3 col-md-3 col-lg-3">
                            <div class="hoverlay">
                                <img src="http://www.nldb.gov.lk/images/portfolio/portfolio_1.png" alt="" />
                                <div class="hoverlay-box">
                                    <div class="hoverlay-data">
                                        <h5>Touch and Swipe</h5>
                                        <span>Technology</span>
                                        <a class="hover-link" href="http://www.nldb.gov.lk/products/Products.asp">
                                            <i class="fa fa-link"></i>
                                        </a>
                                        <a class="hover-zoom mfp-image" href="http://www.nldb.gov.lk/images/portfolio/full/portfolio_1.png">
                                            <i class="fa fa-search"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </li>

                        <!-- Recent Work Item -->
                        <li class="col-sm-3 col-md-3 col-lg-3">
                            <div class="hoverlay">
                                <img src="http://www.nldb.gov.lk/images/portfolio/portfolio_2.png" alt="" />
                                <div class="hoverlay-box">
                                    <div class="hoverlay-data">
                                        <h5>Touch and Swipe</h5>
                                        <span>Technology</span>
                                        <a class="hover-link" href="http://www.nldb.gov.lk/products/Products.asp">
                                            <i class="fa fa-link"></i>
                                        </a>
                                        <a class="hover-zoom mfp-image" href="http://www.nldb.gov.lk/images/portfolio/full/portfolio_1.png">
                                            <i class="fa fa-search"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <!-- Recent Work Item -->
                        <li class="col-sm-3 col-md-3 col-lg-3">
                            <div class="hoverlay">
                                <img src="http://www.nldb.gov.lk/images/portfolio/portfolio_10.png" alt="" />
                                <div class="hoverlay-box">
                                    <div class="hoverlay-data">
                                        <h5>Touch and Swipe</h5>
                                        <span>Technology</span>
                                        <a class="hover-link" href="http://www.nldb.gov.lk/products/Products.asp">
                                            <i class="fa fa-link"></i>
                                        </a>
                                        <a class="hover-zoom mfp-image" href="http://www.nldb.gov.lk/images/portfolio/full/portfolio_1.png">
                                            <i class="fa fa-search"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </li>

                        <!-- Recent Work Item -->
                        <li class="col-sm-3 col-md-3 col-lg-3">
                            <div class="hoverlay">
                                <img src="http://www.nldb.gov.lk/images/portfolio/portfolio_3.png" alt="" />
                                <div class="hoverlay-box">
                                    <div class="hoverlay-data">
                                        <h5>Touch and Swipe</h5>
                                        <span>Technology</span>
                                        <a class="hover-link" href="http://www.nldb.gov.lk/products/Products.asp">
                                            <i class="fa fa-link"></i>
                                        </a>
                                        <a class="hover-zoom mfp-image" href="http://www.nldb.gov.lk/images/portfolio/full/portfolio_1.png">
                                            <i class="fa fa-search"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </li>

                        <!-- Recent Work Item -->
                        <li class="col-sm-3 col-md-3 col-lg-3">
                            <div class="hoverlay">
                                <img src="http://www.nldb.gov.lk/images/portfolio/portfolio_4.png" alt="" />
                                <div class="hoverlay-box">
                                    <div class="hoverlay-data">
                                        <h5>Touch and Swipe</h5>
                                        <span>Technology</span>
                                        <a class="hover-link" href="http://www.nldb.gov.lk/products/Products.asp">
                                            <i class="fa fa-link"></i>
                                        </a>
                                        <a class="hover-zoom mfp-image" href="http://www.nldb.gov.lk/images/portfolio/full/portfolio_1.png">
                                            <i class="fa fa-search"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </li>

                        <!-- Recent Work Item -->
                        <li class="col-sm-3 col-md-3 col-lg-3">
                            <div class="hoverlay">
                                <img src="http://www.nldb.gov.lk/images/portfolio/portfolio_5.png" alt="" />
                                <div class="hoverlay-box">
                                    <div class="hoverlay-data">
                                        <h5>Touch and Swipe</h5>
                                        <span>Technology</span>
                                        <a class="hover-link" href="http://www.nldb.gov.lk/products/Products.asp">
                                            <i class="fa fa-link"></i>
                                        </a>
                                        <a class="hover-zoom mfp-image" href="http://www.nldb.gov.lk/images/portfolio/full/portfolio_1.png">
                                            <i class="fa fa-search"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </li>

                        <!-- Recent Work Item -->
                        <li class="col-sm-3 col-md-3 col-lg-3">
                            <div class="hoverlay">
                                <img src="http://www.nldb.gov.lk/images/portfolio/portfolio_6.png" alt="" />
                                <div class="hoverlay-box">
                                    <div class="hoverlay-data">
                                        <h5>Touch and Swipe</h5>
                                        <span>Technology</span>
                                        <a class="hover-link" href="http://www.nldb.gov.lk/products/Products.asp">
                                            <i class="fa fa-link"></i>
                                        </a>
                                        <a class="hover-zoom mfp-image" href="http://www.nldb.gov.lk/images/portfolio/full/portfolio_1.png">
                                            <i class="fa fa-search"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </li>

                        <!-- Recent Work Item -->
                        <li class="col-sm-3 col-md-3 col-lg-3">
                            <div class="hoverlay">
                                <img src="http://www.nldb.gov.lk/images/portfolio/portfolio_7.png" alt="" />
                                <div class="hoverlay-box">
                                    <div class="hoverlay-data">
                                        <h5>Touch and Swipe</h5>
                                        <span>Technology</span>
                                        <a class="hover-link" href="http://www.nldb.gov.lk/products/Products.asp">
                                            <i class="fa fa-link"></i>
                                        </a>
                                        <a class="hover-zoom mfp-image" href="http://www.nldb.gov.lk/images/portfolio/full/portfolio_1.png">
                                            <i class="fa fa-search"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </li>

                        <!-- Recent Work Item -->
                        <li class="col-sm-3 col-md-3 col-lg-3">
                            <div class="hoverlay">
                                <img src="http://www.nldb.gov.lk/images/portfolio/portfolio_8.png" alt="" />
                                <div class="hoverlay-box">
                                    <div class="hoverlay-data">
                                        <h5>Touch and Swipe</h5>
                                        <span>Technology</span>
                                        <a class="hover-link" href="http://www.nldb.gov.lk/products/Products.asp">
                                            <i class="fa fa-link"></i>
                                        </a>
                                        <a class="hover-zoom mfp-image" href="http://www.nldb.gov.lk/images/portfolio/full/portfolio_1.png">
                                            <i class="fa fa-search"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </li>
					<!-- Recent Work Item -->
                        <li class="col-sm-3 col-md-3 col-lg-3">
                            <div class="hoverlay">
                                <img src="http://www.nldb.gov.lk/images/portfolio/portfolio_9.png" alt="" />
                                <div class="hoverlay-box">
                                    <div class="hoverlay-data">
                                        <h5>Touch and Swipe</h5>
                                        <span>Technology</span>
                                        <a class="hover-link" href="http://www.nldb.gov.lk/products/Products.asp">
                                            <i class="fa fa-link"></i>
                                        </a>
                                        <a class="hover-zoom mfp-image" href="http://www.nldb.gov.lk/images/portfolio/full/portfolio_1.png">
                                            <i class="fa fa-search"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>